/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_airtalkee_TaxiAirTalkee */

#ifndef _Included_cn_com_tiros_airtalkee_TaxiAirTalkee
#define _Included_cn_com_tiros_airtalkee_TaxiAirTalkee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_tiros_airtalkee_TaxiAirTalkee
 * Method:    sys_AirTalkeeEvent
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_airtalkee_TaxiAirTalkee_sys_1AirTalkeeEvent
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
