/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_Gps */

#ifndef _Included_cn_com_tiros_api_Gps
#define _Included_cn_com_tiros_api_Gps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_tiros_api_Gps
 * Method:    sys_gpsChange
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Gps_sys_1gpsChange
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
