/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_LLocation */

#ifndef _Included_cn_com_tiros_api_LLocation
#define _Included_cn_com_tiros_api_LLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_tiros_api_LLocation
 * Method:    sys_llocationNotify
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_LLocation_sys_1llocationNotify
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
