/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_baidu_BaiduLocation */

#ifndef _Included_cn_com_tiros_baidu_BaiduLocation
#define _Included_cn_com_tiros_baidu_BaiduLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_tiros_baidu_BaiduLocation
 * Method:    sys_baiduLocationChange
 * Signature: (IDDDDD)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_baidu_BaiduLocation_sys_1baiduLocationChange
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
