/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_mobnote_logic_GolukLogicJni */

#ifndef _Included_cn_com_mobnote_logic_GolukLogicJni
#define _Included_cn_com_mobnote_logic_GolukLogicJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    GolukLogicCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_GolukLogicCreate
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    GolukLogicDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_GolukLogicDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    GolukLogicRegisterNotify
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_GolukLogicRegisterNotify
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    GolukLogicCommRequest
 * Signature: (JIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_GolukLogicCommRequest
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    GolukLogicCommGet
 * Signature: (JIILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_GolukLogicCommGet
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     cn_com_mobnote_logic_GolukLogicJni
 * Method:    CommRequestEx
 * Signature: (JIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_com_mobnote_logic_GolukLogicJni_CommRequestEx
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
