/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_mobonote_golukmobile_comm_GolukMobileJni */

#ifndef _Included_cn_com_mobonote_golukmobile_comm_GolukMobileJni
#define _Included_cn_com_mobonote_golukmobile_comm_GolukMobileJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_Create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1Create
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_WifiStateChanged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1WifiStateChanged
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_RegistNetTransNotify
 * Signature: (ILcn/com/mobonote/golukmobile/comm/INetTransNotifyFn;)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1RegistNetTransNotify
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_RegistPageNotify
 * Signature: (ILcn/com/mobonote/golukmobile/comm/IPageNotifyFn;)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1RegistPageNotify
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     cn_com_mobonote_golukmobile_comm_GolukMobileJni
 * Method:    GoLuk_CommonGetPage
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_mobonote_golukmobile_comm_GolukMobileJni_GoLuk_1CommonGetPage
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
