/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_mobnote_tachograph_comm_IPCManagerJNI */

#ifndef _Included_cn_com_mobnote_tachograph_comm_IPCManagerJNI
#define _Included_cn_com_mobnote_tachograph_comm_IPCManagerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_Create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1Create
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_RegisterNetTransNotify
 * Signature: (ILcn/com/mobnote/tachograph/comm/IPCManagerFn;)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1RegisterNetTransNotify
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_WifiStateChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1WifiStateChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_SetMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1SetMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_VDCP_CommRequest
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1VDCP_1CommRequest
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_SetGpsInfo
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1SetGpsInfo
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     cn_com_mobnote_tachograph_comm_IPCManagerJNI
 * Method:    IPCManager_AddDownloadFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_com_mobnote_tachograph_comm_IPCManagerJNI_IPCManager_1AddDownloadFile
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
